services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env  # Load the .env file here
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#     POSTGRES_HOST_AUTH_METHOD: trust # for debugging ONLY
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  elasticsearch_app:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch_app
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 20s
      timeout: 7s
      retries: 5

  streamlit_app:
    build:
      context: ./app
    image: python:3.10-slim
    container_name: streamlit_app
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  
      - ./app/app_data:/app/app_data  
    depends_on:
      elasticsearch_app:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml  
      - ./monitoring/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/grafana-dashboard.json  
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - postgres_db
    restart: always

volumes:
  db_data:
  es_data:
  grafana_data:
