{
 "title": "Chatbot Analytics",
 "time": { "from": "2024-10-03T15:54:44.807Z", "to": "2024-10-03T16:48:05.838Z" },
 "panels": [
  {
   "title": "Total Tokens by interaction type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_tokens), interaction_type FROM usage_stats WHERE total_tokens IS NOT NULL GROUP BY interaction_type ORDER BY SUM(total_tokens) DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Token usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT total_tokens, created_at FROM usage_stats WHERE total_tokens IS NOT NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of interaction types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(interaction_count) AS avg_int_ct, interaction_type\nFROM (\n    SELECT COUNT(interaction_type) AS interaction_count, interaction_type, session_id\n    FROM usage_stats\n    WHERE session_id IS NOT NULL\n    GROUP BY interaction_type, session_id\n) AS interaction_counts\nGROUP BY interaction_type\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Total Interactions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT interaction_type, COUNT(session_id) FROM usage_stats WHERE session_id IS NOT NULL GROUP BY interaction_type ORDER BY COUNT(session_id) DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Queries per session-id",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT session_id, COUNT(question) FROM conversations WHERE session_id IS NOT NULL GROUP BY session_id LIMIT 50 "
    }
   ]
  },
  {
   "title": "Queries by language",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), language FROM conversations WHERE COALESCE(language, '') <> '' GROUP BY language LIMIT 50 "
    }
   ]
  },
  {
   "title": "Feedback over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT feedback, created_at FROM feedback LIMIT 50 "
    }
   ]
  }
 ]
}